on:
  schedule: 
  - cron: "0 0 * * *"
jobs:
  setup-custodian:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: ./image-cleanup
      env: 
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: us-east-2
      with: 
        days: 1
