name: Packer Build

on:
  push: 
    paths:
    - 'test/**'
    - '.github/**'

jobs:
  packer-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: ./packer-build
      env: 
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      with: 
        working_dir: test
        template: ubuntu.json

